POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRyaWJibGUiLCJpZCI6IjYyN2JlZmYyM2I4YWEzZjVmMGRiYzhhMiIsImlhdCI6MTY1MjI4OTU0MH0.G7c0MazN8AIoFDlMemCkoSKlkc67M7O6NtZQOjBWecY

{
    "title": "The Poople with Pooples",
    "author": "Joe Pooples",
    "url": "https://www.pooples.com",
    "userId": "627bda983f0a7d0fcb8c86ff"
}

