POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRyaWJibGUiLCJpZCI6IjYyN2M2NWFjZTYyMjUwYWQwOGRjYWM2ZCIsImlhdCI6MTY1MjMxOTY4M30.gx2Bg7pdlSZxQ6ngms-f4o0V8D6QEAsq2kyD4LxW7ok

{
    "title": "The Poople with Pooples",
    "author": "Joe Pooples",
    "url": "https://www.pooples.com",
    "userId": "627bda983f0a7d0fcb8c86ff"
}

