PUT http://localhost:3003/api/blogs/6279743ff91c060981c57406
Content-Type: application/json

{
    "title": "More Tribbles",
    "author": "Wilbur G. George",
    "url": "https://tribbles.google.com/",
    "likes": 213
}